# 19/05/2025

# @ Feature Engineering

# @ Relationship Between the Random variables :
- X:height of a student

- Y:Weight of a student

- Q. find is there any relationship between X and Y?

- Class---->taken --->student--->

- X increases---->y increses?

- X increases---->Y decreases?

# @ We have a three measures for this
 - Co-variance
 - Pearsen coefficient of correlation
 - Spearmens rank correlations

 # 1 . Co-Variance 
 - Somewhat similar to variance
 - If we have two RV X and Y and we find the covariance by changeing the measures then the covariance will change this is a drawback of covariance 
 - This is solved using Pearson coefficient of correlation
 - Corelation doesn't imply the causation
 - X and Y -------> RV
 - corr(X,Y)----->it doesn't mean that X causes Y or Y causes X


In [7]:
import numpy as np 

In [8]:
height=np.array([140,145,160,155,165,170])
weight=np.array([45,48,50,56,60,65])
cv=np.cov(height,weight)
cv  #it gives covariance matrix

array([[134.16666667,  80.        ],
       [ 80.        ,  58.8       ]])

In [9]:
cv[0,1]

np.float64(80.0)

In [10]:
# convert the height into inches and weight into lbs
height_inch = height * 0.4
weight_lbs = weight * 2.2
cv2 = np.cov(height_inch,weight_lbs)
cv2

array([[ 21.46666667,  70.4       ],
       [ 70.4       , 284.592     ]])

 # 2. Pearson's Coefficient of Correlation
 - rho = con(x,y)/sd(x)*sd(y)
 - np.corrcoef(x,y)
 - Pearson coefficient of correlation will work good when the relationship is linear
 - If the relationship is non linear then the value of rho is 0

In [11]:
height=np.array([140,145,160,155,165,170])
weight=np.array([45,48,50,56,60,65])
rho=np.corrcoef(height,weight)
rho

array([[1.        , 0.90069761],
       [0.90069761, 1.        ]])

# 3. Spearmanr Rank Correlation
  - Let we have two random variables X and Y from this two random variable we are creating the new random variable and we will
    find the pearson coefficient of correlation for new random variables 
  - Syntax : from scipy.stas as stats import spearmanr
  - rho = spearmanr(x,y)

In [12]:
from scipy.stats import spearmanr

In [13]:
import scipy.stats as stats

In [14]:
rho=spearmanr(height,weight)
rho

SignificanceResult(statistic=np.float64(0.942857142857143), pvalue=np.float64(0.0048046647230320545))

 Q. Correalation doesnt imply the causation

 # @ Confidence Interval : (CI)

 - X --- RV 
 - x~Distribution(mean,SD)
 - Polulation mean = meu
 - sample mean = (x-bar)
 - x --- heights of people
 - Sample from population of a size :
 - X=x1,x2,x3-----------x30
 - Task --- We want to estimate the Populatiion mean?
 - Estimating the population mean --- meu = (x-bar) (approx.) --- we called it is as point estimation 
   if we increse the sample size the sample mean is going closer to the population mean
 - scenario : X~dist(mean,SD)
 - Sample size = n=30
 - x1,x2-----------x30
 - Statement : meu is lies [158.6,170.2] with 95 % Probability
 -  [158.6,170.2] --- interval
 -  95 % --- confidence --- (c)
 - Formula of CI = (x-bar)+/- z Score * (SD/sqrt(n)) ------ task : def CI(sample,samples_size) : 1.  mean 2. sd 3. n 4. z_score
 - We wanr to estimate mean ---
 - x~GD --- empirical properties ----
 - c = 78.2% -------  First range of SD
 - c = 95%   -------  sec
 - c = 99.7%
 - Suppose we want to get the value of c = 80%,90% ---
 - X~ Non Gaussian Distribution ---
 - chebtshevs inquality --- 1 range --- 75%
 - Suppose we want to get the value of c = 80%,90% ---
 - 1. t-distribution or student t-distribution
   (theoretical way)---->table
 - 2. Bootstrap

# @ 22/5/2025

 # @ X~any Distribution :
 - We have only one sample
 - Task : Give the CI for median with Probability of 95%
 - S --- x1,x2,x3 --- xn --- n=10 Take a random sample from the original sample  k - sample --- k = 1000 --- sampling with repetation
   it is giving the k random sample by using discrete uniform distribution
 - S! = x11,x12 --- x15
 - S2 = x1,x2 --- x5
 - sk

 - s1 --- m1
 - s2 --- m2
 - s3 --- m3
 - sk --- mk

 - sort all the medians of a samples
 - m1<=m2<=m3<=m4 --- <=mk
 - 95%----CI

 - m1,m2,m3 --- m1000
 - m25 --- 2.5 %
 - m975 --- 97.5%
 - median lies in [m25,m975] with a probabilty of 0.95

In [15]:
def empirical_bootstarp(data,k,k_size,c):
    median = []
    for i in range(k):
        s = np.random.choice(data,size=k_size,replace=True)
        median.append(np.median(s))
    median.sort()
    low = (100 - c)/2
    high = c+low
    return np.percentile (median, low ),np.percentile(median, high)
data = [158,155,166,164,170,176,178,180,184]
k = 1000
k_size = 5
c = 80
print(empirical_bootstarp(data,k,k_size,c))
      

(np.float64(164.0), np.float64(178.0))
